name: Code Quality

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  code-quality:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black isort flake8 pylint
        pip install -r requirements.txt

    - name: Check code formatting with Black
      run: |
        black --check --diff .

    - name: Check import sorting with isort
      run: |
        isort --check-only --diff .

    - name: Lint with flake8
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=88 --statistics

    - name: Type checking (if you add type hints)
      run: |
        # Uncomment if you want to add mypy type checking
        # pip install mypy django-stubs
        # mypy --ignore-missing-imports .
        echo "Type checking skipped (add mypy for type hints)"

    - name: Check for code complexity
      run: |
        # Install and run radon for complexity analysis
        pip install radon
        radon cc . -a -nc

    - name: Generate code quality report
      if: always()
      run: |
        echo "## Code Quality Report" > quality-report.md
        echo "- Code formatting checked ✅" >> quality-report.md
        echo "- Import sorting verified ✅" >> quality-report.md
        echo "- Linting completed ✅" >> quality-report.md
        echo "- Complexity analysis done ✅" >> quality-report.md

    - name: Upload quality report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: quality-report
        path: quality-report.md
